import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import NavBar from "./Components/NavBar";
import { Sora } from 'next/font/google'
import Footer from "./Components/Footer";
const sora = Sora({
  subsets: ['latin'],
  display: 'swap',          
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${sora.className} antialiased`}
      >
        <NavBar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
